package com.kafkaproducer.helper;

import java.util.List;

public class Symbols {
    public static final List<String> SYMBOLS = List.of(
            "AAPL",
            "AMZN",
            "MSFT",
            "GOOGL",
            "GOOG",
            "META",
            "TSLA",
            "NVDA",
            "NFLX",
            "AMD",
            "INTC",
            "IBM",
            "ORCL",
            "CRM",
            "ABNB",
            "BABA",
            "BAC",
            "BA",
            "CAT",
            "CSCO",
            "CMCSA",
            "C",
            "COST",
            "CVS",
            "CVX",

            "DIS",
            "DAL",
            "DE",
            "DELL",
            "DOCU",
            "EBAY",
            "ECL",
            "EMR",
            "EXPE",
            "F",
            "GM",
            "GE",
            "GS",
            "HD",
            "HON",
            "IBM",
            "ISRG",
            "JNJ",
            "JPM",

            "KO",
            "KHC",
            "LLY",
            "LMT",
            "MA",
            "MCD",
            "MDT",
            "MMM",
            "MO",
            "MRK",
            "NKE",
            "NOC",
            "NEM",
            "NEP",
            "NTES",

            "ORCL",
            "PANW",
            "PEP",
            "PFE",
            "PG",
            "PLTR",
            "PYPL",
            "QCOM",
            "RBLX",
            "RIVN",
            "RTX",
            "SBUX",
            "SHOP",
            "SNAP",
            "SONY",
            "SPOT",
            "SQ",
            "T",
            "TSLA",

            "TM",
            "TSM",
            "UBER",
            "UNH",
            "UPS",
            "V",
            "VZ",
            "WMT",
            "WFC",
            "XOM",
            "ZM",
            "ZS"
    );

}
